title: Yunfan Jiang's Homepage
page-top-title: A CS Puzzle Solver
top-section-bg-text: Software Engineer | Gen AI
home-subtitle: Yunfan Jiang
copyright-text: '&copy; Yunfan Jiang 2023-2024. All Rights Reserved.'
